baseURL: "https://lyy18659658512.github.io/my_resume/"
languageCode: "en-us"
title: "简历 | 李毅宇"
disableKinds: ["taxonomy", "term", "page", "section", "RSS", "sitemap", "robotsTXT", "404"]
theme: "resume-a4"


# 主列、侧栏和附加页面均由 features 构建
# 每个列和页面都可以包含任意 feature。部分 feature 使用通用组件渲染，你也可以轻松添加新 feature，只要有对应的组件即可。
#
# 常用字段：
#   feature: 功能名称。对于通用 feature，这也是 yaml 文件中的根 key。
#   title: 该元素的标题字符串。设为空字符串可禁用标题。
#   collection: 数据来源的 yaml 文件名，默认为 "features"。
#   widget: 用于渲染该元素的组件路径，如 `layout/partials/section-<widget>.html`。
#
# 常用组件：
#
#   details-list:
#     默认使用（如果没有 section-<feature>.html 文件）。
#
#     数据格式（在 yaml 文件中）：
#       title: 标题字符串
#       subtitle: 副标题，如公司/证书机构等
#       date: 日期字符串，如证书颁发时间
#       details: 详细描述，支持 markdown
#       link: 标题的链接地址
#       links: 详情下方的链接列表
#         prefix: 链接前缀
#         title: 链接文本
#         url: 链接目标地址
#         icon: 图标字符串，如 "fas fa-cloud"，显示在链接和标题后
#
#   word-list:
#     适合技能、兴趣等列表
#
#     附加字段：
#       style: 列表渲染风格，可选 list、compact、title-list
#
#     数据格式（在 yaml 文件中）：
#       如果 style 为 "list"，则为字符串列表
#
#       或如下结构：
#         groupName: 分组标题
#         list: 分组下的字符串列表

params:
  useFontAwesome: true
  externalLinkIcon: true
  css:
    - custom.scss
#   - print_urls.scss
  header:
    avatar: "img/resumephoto.jpg" # 控制是否显示头像 （ResumePhoto.png）
    contact: false # 控制是否显示联系方式（phone、email）
    tagline: true
    links: false
  pages:
    - side:
        #- feature: languages
        #  title: 语言能力
        - feature: skills
          title: 技能证书
          widget: word-list
          style: title-list # list, compact, title-list
        - feature: education
          title: 教育背景
        - feature: awards
          widget: word-list        # 新增
          title: 获奖经历
          style: list
        - feature: interests
          title: 兴趣爱好
          widget: word-list
          style: list

      features:
        - feature: about
          title: 职业概述
        - feature: experience
          title: 工作经历


  experience:
    tools: 
      show: false
      title: Technologies
  education:
    useFontAwesome: true
    externalLinkIcon: false
    location:
      show: false
    details:
      show: false     
    namePrimary: false
  publications:
    useFontAwesome: false
    externalLinkIcon: false
  itemTitle:
    useFontAwesome: false
    externalLinkIcon: false
        
  footer:
    show: false
    credits: true
    footnote: >-
      You can print this resume in A4 size or save as pdf. | Last update on 2020-09-01.
    links:
      - prefix: Contact me on
        title: Linkedin
        url: 'https://linkedin.com/in/mertbakir/'
        icon: fab fa-linkedin
      - prefix: Check out my
        title: Website
        url: 'https://mertbakir.gitlab.io/about/'
        icon: fas fa-globe
